AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This sam-template ONLY exists to build the app, CDK is used to deploy it. DO NOT USE THIS TEMPLATE FOR DEPLOYING

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  bunq2ynab:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bunq2ynab/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment: 
        Variables: 
          SSM_PARAM: '/lambda/bunq2ynab'
          LOG_LEVEL: 'DEBUG'
          LIST_MODE: '0'
        
