AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This application syncs BUNQ transactions to YNAB. After deployment you FIRST need
  to add your BUNQ api_token and YNAB accesstoken. To the SSM parameter. Next you 
  need to run the function to list your accounts and budgets. Add these to your SSM 
  parameter as well. Finally set the LIST_MODE environment variable to 0. 

Metadata:
  AWS::ServerlessRepo::Application:
    Name: bunq-ynab-aws-lambda
    Description:  >
      This application syncs BUNQ transactions to YNAB. You need to run the function 
      to list your accounts and budgets. Next add these to your SSM parameter json. 
      Finally set the LIST_MODE environment variable to 0. Full instructions in the
      README file.
    Author: Javy de Koning
    ReadmeUrl: README.md
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    Labels: ['Bunq', 'Ynab']
    HomePageUrl: https://github.com/javydekoning/bunq-ynab-aws-lambda
    SemanticVersion: 0.1.0
    SourceCodeUrl: https://github.com/javydekoning/bunq-ynab-aws-lambda

Parameters:
  BunqApiToken:
    Type: String
    Description: Your BUNQ API Token
  YnabAccessToken:
    Type: String
    Description: Your YNAB access token
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
  Function:
    Timeout: 30

Resources:
  bunq2ynab:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bunq2ynab/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment: 
        Variables: 
          SSM_PARAM: 
            Ref: ConfigJSON
          LOG_LEVEL: 'INFO'
          LIST_MODE: '1'
      Policies:
        - Statement:
          - Sid: SSMGetPutPolicy
            Effect: Allow
            Action:
            - ssm:GetParameter
            - ssm:PutParameter
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ConfigJSON}'
      Events:
        CloudWatchCronEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

  ConfigJSON:
    Type: AWS::SSM::Parameter
    Properties:
      Name: bunq2ynab
      Type: String
      Value: !Sub >
        {
        	"bunq": {
        		"api_token": "${BunqApiToken}",
        		"priv_key": "",
        		"install_token": "",
        		"session_token": ""
        	},
        	"bunq2ynab": [{
        			"bunq_user": "",
        			"bunq_acc": "",
        			"ynab_budget": "",
        			"ynab_acc": ""
        		},
        		{
        			"bunq_user": "",
        			"bunq_acc": "",
        			"ynab_budget": "",
        			"ynab_acc": ""
        		}
        	],
        	"ynab": {
        		"accesstoken": "${YnabAccessToken}",
        		"clientid": "",
        		"clientsecret": ""
        	}
        }